apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.app.name }}
        ports:
        - containerPort: {{ .Values.service.port }}
        startupProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 35
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.service.port }}
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
        env:
        - name: DATABASE_HOST
          value: {{ .Values.database.host }}
        - name: DATABASE_PORT
          value: "{{ .Values.database.port }}"
        - name: DATABASE_NAME
          value: {{ .Values.database.name }}
        - name: DATABASE_USER
          value: {{ .Values.database.user }}
        - name: DATABASE_PASSWORD
          value: {{ .Values.database.password }}
